/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Analista;

import Analista.Analista;
import Cliente.Cliente;
import Interfaces.Login.Login;
import interfaces.AlterarSenha;
import interfaces.BuscarChamado;
import interfaces.GerenteDeJanelas;
import interfaces.GetSobre;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class MenuAS extends javax.swing.JFrame {

    MeusChamados mc;
    ReceberChamado rc = new ReceberChamado();
    BuscarChamado bc;
    EditarPerfil ep;
    AlterarSenha as;
    GetSobre gs = new GetSobre();
    GerenteDeJanelas gerenteDeJanelas;
    Analista analista = null;
    Atualizados analizados;
    
    public MenuAS() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.panelMenuAS.setMaximumSize(this.getMaximumSize());
        this.panelMenuAS.setMinimumSize(this.getMaximumSize());
        this.gerenteDeJanelas = new GerenteDeJanelas(panelMenuAS);
        this.bc = new BuscarChamado(this.gerenteDeJanelas);
        mc  = new MeusChamados(this.gerenteDeJanelas);
        analizados  = new Atualizados(this.gerenteDeJanelas);
        this.analista = Login.getAnalista();
        if(this.analista==null){
            JOptionPane.showMessageDialog(null,"Login não detectado!","Falha ao efetuar login",3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuAS = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        receberChamado = new javax.swing.JMenuItem();
        buscarChamado = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        meusChamados = new javax.swing.JMenuItem();
        atualizados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        alterPerfil = new javax.swing.JMenuItem();
        alterPass = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        getSobre = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(908, 542));

        javax.swing.GroupLayout panelMenuASLayout = new javax.swing.GroupLayout(panelMenuAS);
        panelMenuAS.setLayout(panelMenuASLayout);
        panelMenuASLayout.setHorizontalGroup(
            panelMenuASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelMenuASLayout.setVerticalGroup(
            panelMenuASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/base.png"))); // NOI18N
        jMenu1.setText("Chamados");

        receberChamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        receberChamado.setText("Receber");
        receberChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receberChamadoActionPerformed(evt);
            }
        });
        jMenu1.add(receberChamado);

        buscarChamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_67_111124.png"))); // NOI18N
        buscarChamado.setText("Buscar");
        buscarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarChamadoActionPerformed(evt);
            }
        });
        jMenu1.add(buscarChamado);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_database_678154.png"))); // NOI18N
        jMenu4.setText("Meus chamados");

        meusChamados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_database_run_103471.png"))); // NOI18N
        meusChamados.setText("Recebidos");
        meusChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meusChamadosActionPerformed(evt);
            }
        });
        jMenu4.add(meusChamados);

        atualizados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_database_security_103472.png"))); // NOI18N
        atualizados.setText("Atualizados");
        atualizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizadosActionPerformed(evt);
            }
        });
        jMenu4.add(atualizados);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit.png"))); // NOI18N
        jMenu2.setText("Editar");

        alterPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit_user.png"))); // NOI18N
        alterPerfil.setText("Meu perfil");
        alterPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(alterPerfil);

        alterPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_Password_372910.png"))); // NOI18N
        alterPass.setText("Alterar senha");
        alterPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterPassActionPerformed(evt);
            }
        });
        jMenu2.add(alterPass);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/setings.png"))); // NOI18N
        jMenu3.setText("Opções");

        getSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/info.png"))); // NOI18N
        getSobre.setText("Sobre");
        getSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSobreActionPerformed(evt);
            }
        });
        jMenu3.add(getSobre);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_icons_exit2_1564506.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu3.add(Logout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuAS)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuAS)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meusChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meusChamadosActionPerformed
        this.mc = new MeusChamados(this.gerenteDeJanelas);
        this.gerenteDeJanelas.abrirJanelas(mc);
    }//GEN-LAST:event_meusChamadosActionPerformed

    private void buscarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarChamadoActionPerformed
        this.gerenteDeJanelas.abrirJanelas(bc);
    }//GEN-LAST:event_buscarChamadoActionPerformed

    private void receberChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receberChamadoActionPerformed
        rc = new ReceberChamado();
        this.gerenteDeJanelas.abrirJanelas(rc);
    }//GEN-LAST:event_receberChamadoActionPerformed

    private void alterPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterPerfilActionPerformed
        ep  = new EditarPerfil(Login.getAnalista().getPessoa());
        this.gerenteDeJanelas.abrirJanelas(ep);
    }//GEN-LAST:event_alterPerfilActionPerformed

    private void alterPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterPassActionPerformed
        as = new AlterarSenha(Login.getAnalista().getPessoa().getNome(), Login.getAnalista().getPessoa().getCPF());
        this.gerenteDeJanelas.abrirJanelas(as);
    }//GEN-LAST:event_alterPassActionPerformed

    private void getSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSobreActionPerformed
        this.gerenteDeJanelas.abrirJanelas(gs);
    }//GEN-LAST:event_getSobreActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login login = new Login();
        Login.setAdmin(null);
        Login.setAnalista(null);
        Login.setCliente(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void atualizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizadosActionPerformed
        this.gerenteDeJanelas.abrirJanelas(this.analizados);
    }//GEN-LAST:event_atualizadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(Login.getAnalista()!=null){
                    new MenuAS().setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null,"Falha em login!","ERRO", 3);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem alterPass;
    private javax.swing.JMenuItem alterPerfil;
    private javax.swing.JMenuItem atualizados;
    private javax.swing.JMenuItem buscarChamado;
    private javax.swing.JMenuItem getSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meusChamados;
    private javax.swing.JDesktopPane panelMenuAS;
    private javax.swing.JMenuItem receberChamado;
    // End of variables declaration//GEN-END:variables
}
