/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces.Analista;

import Chamados.Chamado;
import Dao.DaoAnalista;
import Dao.DaoChamado;
import Interfaces.Login.Login;
import interfaces.GerenteDeJanelas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author 201612030327
 */
public class MeusChamados extends javax.swing.JInternalFrame {

    /**
     * Creates new form MeusChamados
     */
    ArrayList<Chamado> chamados;
    int index_atual = 0;
    DaoChamado dc = new DaoChamado();
    DaoAnalista dA = new DaoAnalista();
    int categoria = 0;
    GerenteDeJanelas gerenteDeJanelas;
    
    public MeusChamados(GerenteDeJanelas gdj) {
        initComponents();
        btProx.setVisible(false);
        btAnt.setVisible(false);
        btSolu.setVisible(false);
        this.gerenteDeJanelas = gdj;
        txtAvaliacao.setVisible(false);
        lbAvaliacao.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox();
        btBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        btProx = new javax.swing.JButton();
        btAnt = new javax.swing.JButton();
        btSolu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btAlterCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSolucao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JTextField();
        lbAvaliacao = new javax.swing.JLabel();
        txtAvaliacao = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Meus chamados!");

        jLabel1.setText("Categoria:");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha uma categoria", "Celulares e telefonia", "TVs", "Projetores", "Antenas, receptores e conversores", "Fotografia e filmadoras", "Computadores", "Notebook e netbook", "Ipad e tablet", "Impressoras e suplementos", "Videogames" }));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Titulo:");

        txtTitulo.setFocusable(false);

        jLabel3.setText("Descrição:");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        txtDesc.setFocusable(false);
        jScrollPane2.setViewportView(txtDesc);

        btProx.setText("Próximo");
        btProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProxActionPerformed(evt);
            }
        });

        btAnt.setText("Anterior");
        btAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAntActionPerformed(evt);
            }
        });

        btSolu.setText("Enviar solução");
        btSolu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSoluActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente:");

        txtCliente.setFocusable(false);

        btAlterCategoria.setText("Alterar categoria");
        btAlterCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterCategoriaActionPerformed(evt);
            }
        });

        txtSolucao.setColumns(20);
        txtSolucao.setRows(5);
        txtSolucao.setFocusable(false);
        jScrollPane1.setViewportView(txtSolucao);

        jLabel5.setText("Solução:");

        jLabel6.setText("Situação:");

        txtSituacao.setFocusable(false);

        lbAvaliacao.setText("Avaliação:");

        txtAvaliacao.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAnt)
                        .addGap(18, 18, 18)
                        .addComponent(btSolu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btProx))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btBuscar))
                            .addComponent(jLabel2)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtCliente))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSituacao)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                                    .addComponent(txtAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btAlterCategoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAvaliacao)
                .addGap(402, 402, 402))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAvaliacao)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btAlterCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSolu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btProx)
                    .addComponent(btAnt))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        this.categoria = cbCategoria.getSelectedIndex();
        LimparTela();
        this.chamados = new ArrayList<Chamado>();
        setChamados();
        if(this.chamados.size() > 0){
            btSolu.setVisible(true);
            cbCategoria.setSelectedIndex(this.categoria);
            visualizar();
        }else{
            btProx.setVisible(false);
            btAnt.setVisible(false);
            btSolu.setVisible(false);
            //JOptionPane.showMessageDialog(null,"Não possui novos chamados nessa categoria!","AVISO",3);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btSoluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSoluActionPerformed
        NovaSolução ns = new NovaSolução(this.chamados.get(this.index_atual));
        this.gerenteDeJanelas.abrirJanelas(ns);
        this.dispose();
    }//GEN-LAST:event_btSoluActionPerformed

    private void btAlterCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterCategoriaActionPerformed
        EditarCategoria ec = new EditarCategoria(this.chamados.get(this.index_atual));
        this.gerenteDeJanelas.abrirJanelas(ec);
    }//GEN-LAST:event_btAlterCategoriaActionPerformed

    private void btProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProxActionPerformed
         if(this.chamados.size()>0){
            if(index_atual==this.chamados.size()-1){
                JOptionPane.showMessageDialog(null,"Esse é o ultimo localizado!", title, HEIGHT);
            }else{
                this.index_atual++;
                visualizar();
            }
        }else{
           JOptionPane.showMessageDialog(null,"Não foi localizado nenhum chamado!","VISUALIZAR",3); 
        }
    }//GEN-LAST:event_btProxActionPerformed

    private void btAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAntActionPerformed
        if(this.chamados.size()>0){
            if(this.index_atual==0){
                JOptionPane.showMessageDialog(null,"Esse é o ultimo localizado!", title, HEIGHT);
            }else{
                this.index_atual--;
                visualizar();
            }
        }else{
           JOptionPane.showMessageDialog(null,"Esse é o primeiro chamado!","VISUALIZAR",3); 
        }
    }//GEN-LAST:event_btAntActionPerformed
    private void visualizar(){
        if(this.dc.estaConectado()){
            if(this.index_atual==0 && this.index_atual!=this.chamados.size()-1){
                btAnt.setVisible(false);
                btProx.setVisible(true);
            }
            else if(this.index_atual==(this.chamados.size()-1) && this.index_atual > 0){
                btProx.setVisible(false);
                btAnt.setVisible(true);
            }else if(this.index_atual>0 && this.index_atual<this.chamados.size()-1){
               btProx.setVisible(true);
               btAnt.setVisible(true); 
            }else if(this.index_atual==0 && this.index_atual==this.chamados.size()-1){
                btAnt.setVisible(false);
                btProx.setVisible(false);
            }
            
            if(cbCategoria.getSelectedItem().toString().equals("Escolha uma categoria")){
                btSolu.setVisible(false);
            }else if(!cbCategoria.getSelectedItem().toString().equals("Escolha uma categoria")){
                btSolu.setVisible(true);
            }
            Chamado atual = this.chamados.get(this.index_atual);
            txtTitulo.setText(atual.getTitulo());
            txtDesc.setText(atual.getDescricao());
            txtCliente.setText(dc.getNomeCliente(atual));
            txtSolucao.setText(atual.getSolucao());
            if(atual.getSituacao()==1){
                txtSituacao.setText("Aberto");
                txtAvaliacao.setVisible(false);
                lbAvaliacao.setVisible(false);
            }else if(atual.getSituacao()==2){
                txtSituacao.setText("Finalizado");
                txtAvaliacao.setText(atual.getAvaliacao()+"");
                txtAvaliacao.setVisible(!false);
                lbAvaliacao.setVisible(!false);
            }else if(atual.getSituacao()==3){
                txtSituacao.setText("Aguardando posicionamento do cliente");              
                txtAvaliacao.setVisible(false);
                lbAvaliacao.setVisible(false);
            }else if(atual.getSituacao()==4){
                txtSituacao.setText("Aguardando posicionamento do analista");
                txtAvaliacao.setVisible(false);
                lbAvaliacao.setVisible(false);
            }else{
                txtSituacao.setText("Indefinida");
                txtAvaliacao.setVisible(false);
                lbAvaliacao.setVisible(false);
            }
            if(atual.getSituacao()==2){
                btSolu.setVisible(false);
            }
        }
    }
    
    private void setChamados(){
        if(this.dc.estaConectado() && this.dA.estaConectado()){
            ArrayList<Chamado> newchamados = dc.chamadosAnalista(""+this.categoria,this.dA.getID(Login.getAnalista()));
            if(newchamados != null && newchamados.size()>0){
                this.chamados = newchamados;
            }else{
                JOptionPane.showMessageDialog(null,"Você não possui chamados pendentes nessa categoria!","AVISO",3);
            }
            
        }
    }
    private void LimparTela(){
        this.chamados = null;
        this.index_atual = 0;
        btProx.setVisible(false);
        btAnt.setVisible(false);
        btSolu.setVisible(false);
        txtCliente.setText("");
        txtDesc.setText("");
        txtTitulo.setText("");
        cbCategoria.setSelectedIndex(0);
        txtSolucao.setText("");
        txtSituacao.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterCategoria;
    private javax.swing.JButton btAnt;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btProx;
    private javax.swing.JButton btSolu;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAvaliacao;
    private javax.swing.JTextField txtAvaliacao;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtSituacao;
    private javax.swing.JTextArea txtSolucao;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
