/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Login;

import Analista.Analista;
import Cliente.Cliente;
import Dao.DaoAdministrador;
import Dao.DaoAnalista;
import Dao.DaoCliente;
import Dao.DaoLogin;
import Dao.DaoPessoa;
import Pessoa.Pessoa;
import administrador.Administrador;
import interfaces.Administrador.MenuADM;
import interfaces.Analista.MenuAS;
import interfaces.Cliente.MenuCL;
import java.security.MessageDigest;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class Entrar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Entrar
     */
    Login janela;
    public Entrar(Login janela) {
        initComponents();
        txtCPF.grabFocus();
        this.janela = janela;
    }


     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Entre com seus dados!");

        jLabel1.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Senha:");

        btEntrar.setText("Entrar");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha)
                            .addComponent(txtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        String CPF = txtCPF.getText().replace(".","");
        CPF = CPF.replace("-","");
        Pessoa pessoa = new Pessoa("",CPF);
        String senha = new String(txtSenha.getPassword());
        try{
            MessageDigest algorithm = MessageDigest.getInstance("SHA-256");
            byte messageDigestSenhaAdmin[] = algorithm.digest(senha.getBytes("UTF-8"));
            StringBuilder hexStringSenhaAdmin = new StringBuilder();
            for (byte b : messageDigestSenhaAdmin) {
            hexStringSenhaAdmin.append(String.format("%02X", 0xFF & b));
            }
            senha = hexStringSenhaAdmin.toString();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"CRIPTOGRAFAR SENHA", HEIGHT);
            senha = null;
        }
        if(senha!=null){
            DaoLogin dL = new DaoLogin();
            if(dL.estaConectado()){
                if(dL.verificaSenha(pessoa, senha)){
                    int papel = dL.getPapel(pessoa);
                    DaoPessoa dP = new DaoPessoa();
                    dP.estaConectado();
                    if(papel==1){
                        DaoAdministrador dA = new DaoAdministrador();  
                        if(dA.estaConectado()){
                            Administrador admin = dA.getAdmin(dP.getId(CPF));
                            admin.setPessoa(dP.getPessoa(CPF));
                            Login.setAdmin(admin);
                            MenuADM menu = new MenuADM();
                            menu.setVisible(true);
                            this.janela.dispose();
                            this.dispose();
                        }
                    }else if(papel==2){
                        DaoAnalista dA = new DaoAnalista();
                        if(dA.estaConectado()){
                            Analista analista = dA.getAnalista(dP.getId(CPF));
                            analista.setPessoa(dP.getPessoa(CPF));
                            Login.setAnalista(analista);
                            MenuAS menu = new MenuAS();
                            menu.setVisible(true);
                            this.janela.dispose();
                            this.dispose();
                        }
                    }else if(papel==3){
                        DaoCliente dC = new DaoCliente();
                        if(dC.estaConectado()){
                            Cliente cliente = dC.getCliente(dP.getId(CPF));
                            cliente.setPessoa(dP.getPessoa(CPF));
                            Login.setCliente(cliente);
                            MenuCL menu = new MenuCL();
                            menu.setVisible(true);
                            this.janela.dispose();
                            this.dispose();
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Falha inesperada!","ERRO", 3);
                    }
                    //JOptionPane.showMessageDialog(null,"Papel: "+papel, "Senha certa", 3);
                }else{
                    txtCPF.setText("");
                    txtSenha.setText("");
                    JOptionPane.showMessageDialog(null,"Dados incorretos, tente novamente!", "Sem correspondência", 3);
                }
            }
        }
    }//GEN-LAST:event_btEntrarActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
