/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Login;

import Analista.Analista;
import Cliente.Cliente;
import administrador.Administrador;
import interfaces.GerenteDeJanelas;

/**
 *
 * @author root
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    GerenteDeJanelas gerenteDeJanelas;
    Entrar entrar;
    Cadastro cadastro = new Cadastro();
    static Analista analista = null;
    static Cliente cliente = null;
    static Administrador admin = null;
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.loginPane.setMaximumSize(this.getMaximumSize());
        this.loginPane.setMinimumSize(this.getMaximumSize());
        this.gerenteDeJanelas = new GerenteDeJanelas(loginPane);
        this.entrar  = new Entrar(this);
        Iniciar();
    }

    public static Analista getAnalista() {
        return analista;
    }

    public static void setAnalista(Analista analista) {
        Login.analista = analista;
    }

    public static Cliente getCliente() {
        return cliente;
    }

    public static void setCliente(Cliente cliente) {
        Login.cliente = cliente;
    }

    public static Administrador getAdmin() {
        return admin;
    }

    public static void setAdmin(Administrador admin) {
        Login.admin = admin;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btLogin = new javax.swing.JButton();
        btCadastro = new javax.swing.JButton();
        loginPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo ao HelpPRO");
        setResizable(false);

        jToolBar1.setBackground(new java.awt.Color(57, 191, 206));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setForeground(new java.awt.Color(40, 175, 163));
        jToolBar1.setRollover(true);

        btLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_Password_372910.png"))); // NOI18N
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jToolBar1.add(btLogin);

        btCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_p.png"))); // NOI18N
        btCadastro.setText("Cadastro");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });
        jToolBar1.add(btCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
            .addComponent(loginPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginPane, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        this.cadastro.dispose();
        this.entrar.dispose();
        this.entrar = new Entrar(this);
        this.gerenteDeJanelas.abrirJanelas(this.entrar);
     
    }//GEN-LAST:event_btLoginActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        this.cadastro.dispose();
        this.entrar.dispose();
        this.cadastro = new Cadastro();
        this.gerenteDeJanelas.abrirJanelas(this.cadastro);
    }//GEN-LAST:event_btCadastroActionPerformed
    
    private void Iniciar(){
        this.cadastro.dispose();
        this.entrar.dispose();
        this.entrar = new Entrar(this);
        this.gerenteDeJanelas.abrirJanelas(this.entrar);
    }
    
    private boolean altoFechar(){
        if(Login.getAdmin()==null || Login.getAnalista()==null || Login.getCliente()==null){
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btLogin;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane loginPane;
    // End of variables declaration//GEN-END:variables


}
