/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Dao.DaoLogin;
import Pessoa.Pessoa;
import java.security.MessageDigest;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class AlterarSenha extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarSenha
     */
    String nome;
    String cpf;
    public AlterarSenha(String nome,String cpf) {
        initComponents();
        this.nome = nome;
        this.cpf = cpf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSenhaAtual = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtSenhaNova = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtConfirmação = new javax.swing.JPasswordField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Alterar senha");

        jLabel1.setText("Senha atual:");

        jLabel2.setText("Nova senha:");

        jLabel3.setText("Confirmar nova senha:");

        jToggleButton1.setText("Alterar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtSenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtSenhaNova)
                            .addComponent(jLabel3)
                            .addComponent(txtConfirmação)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        DaoLogin dl = new DaoLogin();
        if(dl.estaConectado()){
            Pessoa pessoa = new Pessoa(this.nome, this.cpf);
            String senha = new String(txtSenhaAtual.getPassword());
            senha = tohex(senha);
            String novasenha = new String(txtSenhaNova.getPassword());
            novasenha = tohex(novasenha);
            String confirmaSenha = new String(txtConfirmação.getPassword());
            confirmaSenha = tohex(confirmaSenha);
            //JOptionPane.showMessageDialog(null, senha, "Senha digitada:", 3);
            if(dl.verificaSenha(pessoa, senha)){
                //JOptionPane.showMessageDialog(null, "senha certa", "TESTE", 3);
                if(novasenha.equals(confirmaSenha)){                 
                    if(dl.alterarSenha(pessoa, novasenha)){
                        JOptionPane.showMessageDialog(null, "senha alterada com sucesso!", "ALTERAR SENHA", 3);
                        this.dispose();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "a nova senha e sua confirmação não condizem!", "ERRO", 3);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "senha incorreta", "AVISO", 3);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private String tohex(String string){
        try{
                        MessageDigest algorithm = MessageDigest.getInstance("SHA-256");
                        byte messageDigestSenha[] = algorithm.digest(string.getBytes("UTF-8")); 
                        StringBuilder hexStringSenha = new StringBuilder();
                        for (byte b : messageDigestSenha) {
                            hexStringSenha.append(String.format("%02X", 0xFF & b));
                        }
                        return hexStringSenha.toString();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null, "Falha ao criptogradasr a senha", "ALTERAR SENHA", 3);
                        return null;
                    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField txtConfirmação;
    private javax.swing.JPasswordField txtSenhaAtual;
    private javax.swing.JPasswordField txtSenhaNova;
    // End of variables declaration//GEN-END:variables
}
