/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import Chamados.Chamado;
import Cliente.Cliente;
import Dao.DaoChamado;
import Dao.DaoCliente;
import Dao.DaoPessoa;
import interfaces.Cliente.EditarChamado;
import interfaces.Cliente.MeusChamados;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class VisualizarChamado extends javax.swing.JInternalFrame {

    ArrayList<Chamado> chamados;
    int index_atual;
    int tamanho;
    GerenteDeJanelas gerenteDeJanelas;
    Cliente cliente;
    String titulo;
    
    public VisualizarChamado(ArrayList<Chamado> recebidos,int editar,GerenteDeJanelas gdj,Cliente cliente,String titulo) {
        initComponents();
        this.cliente = cliente;
        this.titulo = titulo;
        this.chamados = recebidos;
        this.index_atual = 0;
        this.tamanho = recebidos.size();
        btProximo.setVisible(false);
        btAnterior.setVisible(false);
        visualizar();
        this.gerenteDeJanelas = gdj;
        if(editar != 2){
            btEditar.setVisible(false);       
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtCLiente = new javax.swing.JTextField();
        txtDtTermino = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAnalista = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSolucao = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextPane();
        txtSituação = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAvaliação = new javax.swing.JTextField();
        txtDtInicio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btProximo = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Chamado!");
        setPreferredSize(new java.awt.Dimension(817, 500));

        jLabel5.setText("Data de termino:");

        txtCLiente.setFocusable(false);
        txtCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCLienteActionPerformed(evt);
            }
        });

        txtDtTermino.setFocusable(false);

        jLabel11.setText("Solução:");

        jLabel6.setText("Analista designado:");

        txtAnalista.setFocusable(false);

        txtSolucao.setEditable(false);
        jScrollPane2.setViewportView(txtSolucao);

        jLabel2.setText("Título:");

        jLabel7.setText("Categoria:");

        txtTitulo.setFocusable(false);

        txtCategoria.setFocusable(false);

        jLabel3.setText("Descrição:");

        jLabel8.setText("Situação:");

        txtDescricao.setFocusable(false);
        jScrollPane1.setViewportView(txtDescricao);

        txtSituação.setFocusable(false);

        jLabel9.setText("Avaliação:");

        jLabel4.setText("Data de inicio:");

        txtAvaliação.setFocusable(false);

        txtDtInicio.setFocusable(false);

        jLabel10.setText("Autor/Cliente:");

        btProximo.setText("Próximo");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btAnterior.setText("Anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnalista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtDtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtSituação, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(30, 30, 30))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5)
                                            .addGap(81, 81, 81)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(309, 309, 309))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAvaliação, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btProximo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSituação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnalista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAvaliação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAnterior)
                            .addComponent(btEditar)
                            .addComponent(btProximo))))
                .addGap(293, 293, 293))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCLienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCLienteActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        if(this.tamanho>0){
            if(index_atual==0){
                JOptionPane.showMessageDialog(null,"Esse é o primeiro!", title, HEIGHT);
            }else{
                this.index_atual--;
                visualizar();
            }
        }else{
           JOptionPane.showMessageDialog(null,"Não foi localizado nenhum chamado!","VISUALIZAR",3); 
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        if(this.tamanho>0){
            if(index_atual==this.tamanho-1){
                JOptionPane.showMessageDialog(null,"Esse é o ultimo localizado!", title, HEIGHT);
            }else{
                this.index_atual++;
                visualizar();
            }
        }else{
           JOptionPane.showMessageDialog(null,"Não foi localizado nenhum chamado!","VISUALIZAR",3); 
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        try{
            Chamado atual = this.chamados.get(this.index_atual);
            EditarChamado ec = new EditarChamado(atual);
            this.gerenteDeJanelas.abrirJanelas(ec);
            DaoChamado dc = new DaoChamado();
            this.dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"FALHA AO TENTAR ABRIR EDIÇÃO",3);
        }
    }//GEN-LAST:event_btEditarActionPerformed
    
    private void visualizar(){
        if(this.tamanho>0){
            DaoChamado dc = new DaoChamado();
            if(dc.estaConectado()){
                try{
                    Chamado atual = this.chamados.get(this.index_atual);
                    txtTitulo.setText(atual.getTitulo());
                    txtDescricao.setText(atual.getDescricao());
                    txtDtInicio.setText(atual.getData_inicio());
                    txtDtTermino.setText(atual.getData_termino());
                    txtCLiente.setText(dc.getNomeCliente(atual));
                    txtCategoria.setText(dc.getNomeCategoria(atual));
                    txtAnalista.setText(dc.getNomeAnalista(atual));
                    txtSituação.setText(dc.getNomeSituacao(atual));
                    txtSolucao.setText(atual.getSolucao());
                    txtAvaliação.setText(""+atual.getAvaliacao());
                    if(this.index_atual==0 && this.index_atual!=this.chamados.size()-1){
                        btAnterior.setVisible(false);
                        btProximo.setVisible(true);
                    }
                    else if(this.index_atual==(this.chamados.size()-1) && this.index_atual!=0){
                        btProximo.setVisible(false);
                        btAnterior.setVisible(true);
                    }else if(this.index_atual>0 && this.index_atual<this.chamados.size()-1){
                        btProximo.setVisible(true);
                        btAnterior.setVisible(true); 
                    }else if(this.index_atual==0 && this.index_atual==this.chamados.size()-1){
                        btAnterior.setVisible(false);
                        btProximo.setVisible(false);
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"VISUALIZAR",3);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Sem conexão com a base de dados!","VISUALIZAR",3);
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Não foi localizado nenhum chamado!","VISUALIZAR",3);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btProximo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAnalista;
    private javax.swing.JTextField txtAvaliação;
    private javax.swing.JTextField txtCLiente;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextPane txtDescricao;
    private javax.swing.JTextField txtDtInicio;
    private javax.swing.JTextField txtDtTermino;
    private javax.swing.JTextField txtSituação;
    private javax.swing.JTextPane txtSolucao;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
