/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Administrador;

import Interfaces.Login.Login;
import administrador.Administrador;
import interfaces.AlterarSenha;
import interfaces.GerenteDeJanelas;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class MenuADM extends javax.swing.JFrame {

   GerenteDeJanelas gerenteDeJanelas;
   BuscarPessoa bp = new BuscarPessoa();
   RemoverPessoa rp = new RemoverPessoa();
   CadastroAnalista ca = new CadastroAnalista();
   CadastroAdmin admin = new CadastroAdmin();
   AlterarSobre sobre = new AlterarSobre();
   AlterarSenha senha = new AlterarSenha(null,null);
    Administrador administrador = Login.getAdmin();
    public MenuADM() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.panelMenuADM.setMaximumSize(this.getMaximumSize());
        this.panelMenuADM.setMinimumSize(this.getMaximumSize());
        this.gerenteDeJanelas = new GerenteDeJanelas(panelMenuADM);

    }
    
    private void disposeOnClosed() {
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuADM = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BuscarPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CadAnalista = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CadAdmin = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AlterDesc = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo!");

        panelMenuADM.setMinimumSize(new java.awt.Dimension(908, 519));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_Username_372902.png"))); // NOI18N
        jMenu1.setText("Pessoa");

        BuscarPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_67_111124.png"))); // NOI18N
        BuscarPessoa.setText("Buscar pessoa");
        BuscarPessoa.setMinimumSize(new java.awt.Dimension(800, 600));
        BuscarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(BuscarPessoa);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_hard-hat--plus_45673.png"))); // NOI18N
        jMenu2.setText("Analista");

        CadAnalista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_p.png"))); // NOI18N
        CadAnalista.setText("Cadastrar analista");
        CadAnalista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadAnalistaActionPerformed(evt);
            }
        });
        jMenu2.add(CadAnalista);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_user-business-gray-boss_46318.png"))); // NOI18N
        jMenu3.setText("Administrador");

        CadAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_p.png"))); // NOI18N
        CadAdmin.setText("Cadastrar administrador");
        CadAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadAdminActionPerformed(evt);
            }
        });
        jMenu3.add(CadAdmin);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/setings.png"))); // NOI18N
        jMenu4.setText("Opções");

        AlterDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/info.png"))); // NOI18N
        AlterDesc.setText("Alterar sobre");
        AlterDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterDescActionPerformed(evt);
            }
        });
        jMenu4.add(AlterDesc);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_icons_exit2_1564506.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu4.add(Logout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuADM, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuADM, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPessoaActionPerformed

        this.gerenteDeJanelas.abrirJanelas(this.bp);
        
    }//GEN-LAST:event_BuscarPessoaActionPerformed

    private void CadAnalistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadAnalistaActionPerformed
        this.gerenteDeJanelas.abrirJanelas(this.ca);
    }//GEN-LAST:event_CadAnalistaActionPerformed

    private void CadAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadAdminActionPerformed
        this.gerenteDeJanelas.abrirJanelas(this.admin);
    }//GEN-LAST:event_CadAdminActionPerformed

    private void AlterDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterDescActionPerformed
        this.gerenteDeJanelas.abrirJanelas(this.sobre);
    }//GEN-LAST:event_AlterDescActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login login = new Login();
        Login.setAdmin(null);
        Login.setAnalista(null);
        Login.setCliente(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(Login.getAdmin()!=null){
                new MenuADM().setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(null,"Localizado uma falha em login! ","ERRO", 3);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlterDesc;
    private javax.swing.JMenuItem BuscarPessoa;
    private javax.swing.JMenuItem CadAdmin;
    private javax.swing.JMenuItem CadAnalista;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane panelMenuADM;
    // End of variables declaration//GEN-END:variables
}
