/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces.Cliente;

import Cliente.Cliente;
import Dao.DaoCliente;
import Dao.DaoPessoa;
import Interfaces.Login.Login;
import javax.swing.JOptionPane;

/**
 *
 * @author 201612030327
 */
public class EditarPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarPerfil
     */
    Cliente cliente = Login.getCliente();
    String CPF_anterior;
    public EditarPerfil() {
        initComponents();
        this.CPF_anterior = this.cliente.getPessoa().getCPF();
        Limpar();
        Visualizar();
    }
    
    private void Visualizar(){
        txtNome.setText(cliente.getPessoa().getNome());
        txtDtnasc.setText(cliente.getPessoa().getDt_nasc());
        txtCPF.setText(cliente.getPessoa().getCPF());
        txtExperiencia.setSelectedIndex(cliente.getNvl_exp());
        txtSexo.setSelectedIndex(cliente.getPessoa().getSexo()-1);
    }
    
    private void Limpar(){
        txtNome.setText("");
        txtDtnasc.setText("");
        txtCPF.setText("");
        txtExperiencia.setSelectedIndex(0);
        txtSexo.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDtnasc = new javax.swing.JFormattedTextField();
        txtSexo = new javax.swing.JComboBox();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExperiencia = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Nome:");

        jLabel2.setText("Sexo:");

        jLabel3.setText("Data de nascimento:");

        jLabel4.setText("CPF:");

        try {
            txtDtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino" }));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Nivel de experiencia:");

        txtExperiencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escolha um nível:", "iniciante", "Pouca experiência", "Conhecimentos básicos", "Exepriente em problemas básicos", "Conhecimento intermediário", "Exeperiente em geral", "Tecnologo em tecnologia", "Graduado em área tecnologica", "Conhecimento avançados", "Profissional" }));

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2))
                                    .addComponent(txtSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(txtDtnasc)
                                    .addComponent(txtExperiencia, 0, 173, Short.MAX_VALUE)))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtExperiencia.getSelectedIndex()!=0){
            this.cliente.setNvl_exp(txtExperiencia.getSelectedIndex());
        }else{
            this.cliente.setNvl_exp(1);
            JOptionPane.showMessageDialog(null,"Você foi classificadoautomaticamente como iniciante","AVISO",3);
        }
        String CPF = txtCPF.getText().replace("-","");
        CPF = CPF.replace(".","");
        this.cliente.getPessoa().setCPF(CPF);
        this.cliente.getPessoa().setDt_nasc(txtDtnasc.getText());
        this.cliente.getPessoa().setSexo(txtSexo.getSelectedIndex()+1);
        this.cliente.getPessoa().setNome(txtNome.getText());
        
        DaoCliente dC = new DaoCliente();
        DaoPessoa dP = new DaoPessoa();
        if(dC.estaConectado() && dP.estaConectado()){
            if(dC.editar(this.cliente,dC.getIdCliente(dP.getId(this.CPF_anterior)),dP.getId(this.CPF_anterior))){
                JOptionPane.showMessageDialog(null,"Seu perfil foi atualizado!","Sucesso", 3);
                Login.setCliente(this.cliente);
                this.dispose();
            }else{
               JOptionPane.showMessageDialog(null,"Ocorreu um erro inesperado!","FALHA", 3);
            }
        }else{
           JOptionPane.showMessageDialog(null,"Sem conexão com a base de dados!","FALHA", 3);
            this.dispose(); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtDtnasc;
    private javax.swing.JComboBox txtExperiencia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JComboBox txtSexo;
    // End of variables declaration//GEN-END:variables
}
