/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Cliente;

import Chamados.Chamado;
import Cliente.Cliente;
import Dao.DaoChamado;
import Dao.DaoCliente;
import Dao.DaoPessoa;
import Interfaces.Login.Login;
import interfaces.AlterarSenha;
import interfaces.BuscarChamado;
import interfaces.GerenteDeJanelas;
import interfaces.GetSobre;
import interfaces.VisualizarChamado;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class MenuCL extends javax.swing.JFrame {

    EditarPerfil ep = new EditarPerfil();
    MeusChamados mc;
    NovoChamado nc = new NovoChamado();
    AlterarSenha as = new AlterarSenha(Login.getCliente().getPessoa().getNome(), Login.getCliente().getPessoa().getCPF());
    GetSobre gs = new GetSobre();
    BuscarChamado bc;  
    GerenteDeJanelas gerenteDeJanelas;

    public MenuCL() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.panelMenuCL.setMaximumSize(this.getMaximumSize());
        this.panelMenuCL.setMinimumSize(this.getMaximumSize());
        this.gerenteDeJanelas = new GerenteDeJanelas(panelMenuCL);
        this.bc = new BuscarChamado(this.gerenteDeJanelas); 
        this.mc = new MeusChamados(this.gerenteDeJanelas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuCL = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirChamado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        meusChamados = new javax.swing.JMenuItem();
        solucionados = new javax.swing.JMenuItem();
        buscarChamados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        alterPerfil = new javax.swing.JMenuItem();
        alterSenha = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        getSobre = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem vindo!");
        setPreferredSize(new java.awt.Dimension(908, 542));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/base.png"))); // NOI18N
        jMenu1.setText("Chamados");

        abrirChamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        abrirChamado.setText("Novo");
        abrirChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirChamadoActionPerformed(evt);
            }
        });
        jMenu1.add(abrirChamado);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_database_678154.png"))); // NOI18N
        jMenu3.setText("Meus chamados");

        meusChamados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_database_security_103472.png"))); // NOI18N
        meusChamados.setText("Meu histórico");
        meusChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meusChamadosActionPerformed(evt);
            }
        });
        jMenu3.add(meusChamados);

        solucionados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_database_run_103471.png"))); // NOI18N
        solucionados.setText("Novos solucionados");
        solucionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solucionadosActionPerformed(evt);
            }
        });
        jMenu3.add(solucionados);

        jMenu1.add(jMenu3);

        buscarChamados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_67_111124.png"))); // NOI18N
        buscarChamados.setText("Buscar");
        buscarChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarChamadosActionPerformed(evt);
            }
        });
        jMenu1.add(buscarChamados);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit.png"))); // NOI18N
        jMenu2.setText("Editar");

        alterPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit_user.png"))); // NOI18N
        alterPerfil.setText("Meu perfil");
        alterPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(alterPerfil);

        alterSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_Password_372910.png"))); // NOI18N
        alterSenha.setText("Alterar senha");
        alterSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterSenhaActionPerformed(evt);
            }
        });
        jMenu2.add(alterSenha);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/setings.png"))); // NOI18N
        jMenu4.setText("Opções");

        getSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/info.png"))); // NOI18N
        getSobre.setText("Sobre");
        getSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getSobreActionPerformed(evt);
            }
        });
        jMenu4.add(getSobre);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/if_icons_exit2_1564506.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu4.add(Logout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuCL, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuCL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarChamadosActionPerformed
        gerenteDeJanelas.abrirJanelas(bc);
    }//GEN-LAST:event_buscarChamadosActionPerformed

    private void abrirChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirChamadoActionPerformed
        if(Login.getCliente().getChamados_num()<5){
            gerenteDeJanelas.abrirJanelas(nc);
        }else{
            JOptionPane.showMessageDialog(null,"Você abriu muitos chamados!\n Aguarde suas resoluções antes de abrir um novo","AVISO",3);
        }
    }//GEN-LAST:event_abrirChamadoActionPerformed

    private void meusChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meusChamadosActionPerformed
        gerenteDeJanelas.abrirJanelas(mc);
    }//GEN-LAST:event_meusChamadosActionPerformed

    private void alterPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterPerfilActionPerformed
        gerenteDeJanelas.abrirJanelas(ep);
    }//GEN-LAST:event_alterPerfilActionPerformed

    private void alterSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterSenhaActionPerformed
        gerenteDeJanelas.abrirJanelas(as);
    }//GEN-LAST:event_alterSenhaActionPerformed

    private void getSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getSobreActionPerformed
        gerenteDeJanelas.abrirJanelas(gs);
    }//GEN-LAST:event_getSobreActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login login = new Login();
        Login.setAdmin(null);
        Login.setAnalista(null);
        Login.setCliente(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void solucionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solucionadosActionPerformed
        DaoChamado dc = new DaoChamado();
        DaoCliente dcliente = new DaoCliente();
        DaoPessoa dp = new DaoPessoa();
        if(dc.estaConectado() && dcliente.estaConectado() && dp.estaConectado()){
            try{
                Cliente cliente = Login.getCliente();
                ArrayList<Chamado> chamados = dc.meusChamados(dcliente.getIdCliente(dp.getId(cliente.getPessoa().getCPF())),3,"");
                if(chamados.size()>0){
                    Solucionados sl = new Solucionados(chamados,this.gerenteDeJanelas);
                    this.gerenteDeJanelas.abrirJanelas(sl);
                }else{
                    JOptionPane.showMessageDialog(null,"Você ainda não possui novos chamados solucionados","AVISO",3);
                }
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erro: "+e.getMessage(),"FALHA AO ABRIR VISUALIZAÇÃO",3);
            }
        }else{
                JOptionPane.showMessageDialog(null,"Não localizou nenhum chamado","BUSCAR",3);
        }
    }//GEN-LAST:event_solucionadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               if(Login.getCliente()!=null){
                    new MenuCL().setVisible(true);
               }else{
                   JOptionPane.showMessageDialog(null,"Falha em login!","ERRO", 3);
               }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem abrirChamado;
    private javax.swing.JMenuItem alterPerfil;
    private javax.swing.JMenuItem alterSenha;
    private javax.swing.JMenuItem buscarChamados;
    private javax.swing.JMenuItem getSobre;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem meusChamados;
    private javax.swing.JDesktopPane panelMenuCL;
    private javax.swing.JMenuItem solucionados;
    // End of variables declaration//GEN-END:variables
}
