/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.Cliente;

import Chamados.Chamado;
import Dao.DaoChamado;
import interfaces.GerenteDeJanelas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class Solucionados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Solucionados
     */
    ArrayList<Chamado> chamados;
    int index_atual = 0;
    DaoChamado dC = new DaoChamado();
    GerenteDeJanelas gerenteDeJanelas;
    public Solucionados(ArrayList<Chamado> chm,GerenteDeJanelas gdj) {
        initComponents();
        this.chamados = chm;
        btAnterior.setVisible(false);
        btProximo.setVisible(false);
        btSolucionado.setVisible(false);
        btNewSolucao.setVisible(false);
        if(this.chamados.size()>0 && dC.estaConectado()){
            visualizar();
            this.gerenteDeJanelas = gdj;
        }else{
            JOptionPane.showMessageDialog(null,"Falha ao obter chamados","ERRO",3);
        }
    }

    public void visualizar(){
        if(this.index_atual==0 && this.index_atual!=this.chamados.size()-1){
                btAnterior.setVisible(false);
                btProximo.setVisible(true);
                btSolucionado.setVisible(true);
                btNewSolucao.setVisible(true);
            }
            else if(this.index_atual==(this.chamados.size()-1) && this.index_atual>0){
                btProximo.setVisible(false);
                btAnterior.setVisible(true);
                btSolucionado.setVisible(true);
                btNewSolucao.setVisible(true);
            }else if(this.index_atual>0 && this.index_atual<this.chamados.size()-1){
               btProximo.setVisible(true);
               btAnterior.setVisible(true);
               btSolucionado.setVisible(true);
               btNewSolucao.setVisible(true);
            }else if(this.index_atual==0 && this.index_atual==this.chamados.size()-1){
                btAnterior.setVisible(false);
                btProximo.setVisible(false);
                btSolucionado.setVisible(true);
                btNewSolucao.setVisible(true);
            }
        Chamado atual = chamados.get(index_atual);
        txtTitulo.setText(atual.getTitulo());
        txtDesc.setText(atual.getDescricao());
        txtSolucao.setText(atual.getSolucao());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSolucao = new javax.swing.JTextArea();
        btNewSolucao = new javax.swing.JButton();
        btSolucionado = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();

        setClosable(true);
        setTitle("Meus chamados devolvidos!");

        jLabel1.setText("Titulo:");

        txtTitulo.setFocusable(false);

        jLabel2.setText("Descrição:");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        txtDesc.setFocusable(false);
        jScrollPane1.setViewportView(txtDesc);

        jLabel3.setText("Solução:");

        txtSolucao.setColumns(20);
        txtSolucao.setRows(5);
        txtSolucao.setFocusable(false);
        jScrollPane2.setViewportView(txtSolucao);

        btNewSolucao.setText("Relatar ao analista");
        btNewSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewSolucaoActionPerformed(evt);
            }
        });

        btSolucionado.setText("Solucionado");
        btSolucionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolucionadoActionPerformed(evt);
            }
        });

        btProximo.setText("Proximo");
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btAnterior.setText("Anterior");
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtTitulo)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addComponent(btAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSolucionado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNewSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btSolucionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btNewSolucao)
                                .addContainerGap(23, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btProximo)
                                .addGap(40, 40, 40))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAnterior)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSolucionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolucionadoActionPerformed
        Avaliacao av = new Avaliacao(this.chamados.get(this.index_atual));
        this.gerenteDeJanelas.abrirJanelas(av);
        this.dispose();
    }//GEN-LAST:event_btSolucionadoActionPerformed

    private void btNewSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewSolucaoActionPerformed
        novaDuvida nD = new novaDuvida(this.chamados.get(this.index_atual));
        this.gerenteDeJanelas.abrirJanelas(nD);
        this.dispose();
    }//GEN-LAST:event_btNewSolucaoActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        if(this.index_atual==0 && this.index_atual!=this.chamados.size()-1){
            this.index_atual++;
            visualizar();
        }else{
            JOptionPane.showMessageDialog(null,"Esse é o ultimo localizado!","AVISO",3);
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        if(this.index_atual>0){
            this.index_atual--;
            visualizar();
        }else{
           JOptionPane.showMessageDialog(null,"Esse é o primeiro localizado!","AVISO",3);
        }
    }//GEN-LAST:event_btAnteriorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btNewSolucao;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btSolucionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextArea txtSolucao;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
